import type { Policy } from "./types";

export const seedPolicies: Policy[] = [
  { id: "hours", title: "Hours and Regular Schedule", body: "Fern Hollow is open Monday through Friday, 6:30am to 6:00pm, year-round. Doors are locked until 6:30am sharp and staff cannot accept children earlier. Core program hours are 9:00am to 3:30pm; drop-off after 9:30am requires a call ahead so the classroom can plan lunch counts." },
  { id: "holidays", title: "Holiday Closures and Special Hours", body: "Fern Hollow closes for: New Year's Day, Memorial Day, Independence Day, Labor Day, Thanksgiving Day and the Friday after, and December 24-25. We are OPEN with normal hours on Veterans Day, MLK Day, and Presidents' Day. Exceptions to normal hours: the Wednesday before Thanksgiving we close early at 3:00pm, and December 26-31 we run reduced hours, 8:00am to 4:00pm, with combined classrooms. Two staff in-service days per year (the second Friday of February and the last Friday of August) are full closures announced 60 days ahead. When a holiday falls on a weekend, we close on the federally observed weekday. Tuition is not reduced for closure days." },
  { id: "tuition", title: "Tuition and Rates", body: "Weekly tuition, effective January 2026: Infants (6 weeks to 12 months) $395; Toddlers (1-2 years) $350; Twos $325; Preschool (3-5 years) $295. Rates change the Monday after a child's classroom transition, which happens the month after their birthday, not on the birthday itself. Part-time (3 days) is 70% of the full weekly rate. A 10% sibling discount applies to the older child's tuition." },
  { id: "payment", title: "Payment, Late Fees, and Deposits", body: "Tuition is due Monday of each week by autopay; accounts unpaid by Wednesday incur a $30 late fee, and care may be suspended if the balance exceeds two weeks. A deposit of two weeks' tuition is collected at enrollment and applied to the final two weeks after 30 days' written withdrawal notice. There is no tuition credit for illness, vacation, holidays, or emergency closures. Returned payments incur a $25 fee." },
  { id: "illness", title: "Illness and Exclusion", body: "Children with a temperature of 100.4°F or higher are sent home and may not return until fever-free for 24 hours without fever-reducing medication. One episode of vomiting or two episodes of diarrhea in a day also means going home, with the same 24-hour symptom-free rule. Children on antibiotics must have completed 24 hours of doses before returning. Undiagnosed rashes, suspected pink eye, and lice require clearance; a doctor's note may be required after any communicable illness. If a child becomes ill at Fern Hollow, we call parents and expect pickup within one hour." },
  { id: "medication", title: "Medication", body: "Staff administer medication only with a signed Medication Authorization form and the medicine in its original, pharmacy-labeled container. Each dose is logged and the log is available to parents on request. We cannot give the first-ever dose of any new medication. Over-the-counter items including sunscreen, diaper cream, and fever reducers also require signed authorization. Emergency medications such as EpiPens and inhalers require an additional doctor-signed action plan kept in the classroom." },
  { id: "meals", title: "Meals and Food", body: "Fern Hollow provides morning snack, afternoon snack, and milk through the USDA Child and Adult Care Food Program (CACFP) at no extra charge. Parents pack lunch daily, labeled with the child's name; we refrigerate and can warm items. Fern Hollow is a nut-free facility. If you forget lunch, tell the front desk by 10:30am: we provide a backup lunch (typically a sunbutter sandwich, fruit, and milk) for a $6 charge to your account. Food allergies require a doctor-signed Allergy Action Plan." },
  { id: "pickup", title: "Drop-off, Pickup, and Late Pickup", body: "Only adults (18+) listed on the authorized pickup list may collect a child, and photo ID is checked until staff know them by sight. After 6:00pm, a late fee of $2 per minute applies, payable on the next invoice. If a child remains at 6:30pm and no contact or emergency contact can be reached, we are required to notify local police and child protective services. Three late pickups in a quarter trigger a required meeting with the director." },
  { id: "tours", title: "Tours and Enrollment", body: "Tours run Tuesdays and Thursdays at 10:00am and 4:00pm and last about 30 minutes; book through the front desk, by phone at (555) 014-2400, or on our website. After touring, families submit an application with a $100 non-refundable registration fee to join the waitlist, which is managed by age group and application date. The infant waitlist is typically 3-6 months; preschool spots often open in August. Enrollment requires an immunization record, health statement, emergency contacts, and the signed tuition agreement." },
  { id: "weather", title: "Weather and Emergency Closures", body: "Fern Hollow follows the Maple Valley School District for weather decisions: if the district closes, we close; if the district delays two hours, we open at 8:30am and skip morning snack. Closure notices go out by 5:45am via app notification and email. Tuition is not credited for weather closures of fewer than five consecutive days." },
  { id: "behavior", title: "Behavior Guidance and Biting", body: "We use positive guidance: redirection, natural consequences, and never physical punishment or withholding food. Biting is treated as a normal developmental stage in infant and toddler rooms; both families are notified with an incident report, but we never share the name of the other child involved. Repeated incidents trigger a documented support plan with the family before any change in enrollment is considered." },
  { id: "custody", title: "Custody and Records", body: "Both legal parents have equal access to their child and records unless a court order on file says otherwise; we must have a copy of any custody order or parenting plan to enforce it. Staff remain neutral in disputes and cannot restrict a parent based on one parent's verbal request alone. Child records, incident reports, and daily notes are shared only with that child's own parents or guardians." },
];
